### ISSUE TITLE
NullPointer Exception due to a insufficient symbol table

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cr0hn/lapse-plus#1]
```
Hi folks,

I was very glad to find the code of Livshits' work and tested it with an 
industrial case study, available at our institute. During the test a null 
pointer exception popped up during the "Find sinks" process.
The source of the exception is the SourceViewClass and a simple patch, which 
fixes my problem and a reproducer, is attached.

The fix solves the symptom but it does not solve the real problem, which is the 
underlying symbol table implemented in DeclarationInfoManager, which does a 
very rough estimation of the available symbols since it does not handle 
inherited fields.

Regards

Bernhard
```

Original issue reported on code.google.com by `berge...@googlemail.com` on 28 Jul 2011 at 4:43

Attachments:
- [Reproducer.zip](https://storage.googleapis.com/google-code-attachments/lapse-plus/issue-1/comment-0/Reproducer.zip)
- [NullPointerBug.patch](https://storage.googleapis.com/google-code-attachments/lapse-plus/issue-1/comment-0/NullPointerBug.patch)

**Comment by saraelaa** [comment]
I don't know how to interpret the results of Lapse plus, how can i know where the vulnerability exists, & is it the line that Provenance Tracker View shows in red???? plz i need help thank you in advance

**Comment by xiaojianbo2017** [comment]
Hi,

After I installed lapsePlus_2.8.3 to my eclipse3.6, I got an error message when i use find sources in Vulnerability Sources tab in eclipse.
 Can you give me some help about this issue?

Thanks1

**Comment by xiaojianbo2017** [comment]
The following is the error message :
!ENTRY org.eclipse.core.jobs 4 2 2017-01-24 12:44:36.298
!MESSAGE An internal error occurred during: "Computing Sinks".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.cacheBinaryType(LookupEnvironment.java:173)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.cacheBinaryType(LookupEnvironment.java:165)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.cacheBinaryType(MatchLocator.java:392)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.cacheBinaryType(MatchLocator.java:379)
	at org.eclipse.jdt.internal.core.search.matching.ClassFileMatchLocator.locateMatches(ClassFileMatchLocator.java:179)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:1634)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1078)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1119)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1251)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:94)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:231)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:515)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:582)
	at lapsePlus.CallerFinder.findCallers(CallerFinder.java:270)
	at lapsePlus.views.SinkView$4.run(SinkView.java:680)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
